config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only:[:index, :show]
  resources :relationships, only:[:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :conversations do
    resources :messages
  end

  resources :topics do
    resources :comments

    collection do
      post :confirm
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :notifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:edit, :update, :destroy]


  def create
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    @notification = @comment.notifications.build(user_id: @topic.user.id )

    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました。' }
        format.json { render :show, status: :created, location: @comment }
        format.js { render :index }
        unless @comment.topic.user.id == current_user
        Pusher.trigger("user_#{@comment.topic.user_id}_channnel", 'comment_created', {
          message: 'Topicにコメントが付きました'
        })
      end
      Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'notification_created', {
          unread_counts: Notification.where(user_id: @comment.topic.user.id, read: false).count
        })
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to topic_path(@comment.topic)
    else
      render :edit
    end
  end

  def destroy
    @commets = @comment.topic.comments
    @comment.destroy
    respond_to do |format|
      format.js { render :index }
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:topic_id, :content)
    end

    def set_comment
      @comment = current_user.comments.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= form_for([topic,comment], remote: true) do |f|
  = f.error_messages!
  = f.hidden_field :topic_id
  .field
    = f.text_field :content, placeholder: "コメント...", class: "form-control"
    %br/
  .actions
    = f.submit '投稿', class: 'btn btn-primary'

app/views/comments/_index.html.haml
%ul
  - comments.each do |comment|
    - unless comment.id.nil?
      %li
        %p.profile_img= profile_img(comment.user)
        %p.left= comment.user.name
        %p.left= comment.content
        - if current_user.id == comment.user.id
          %p.right
            = link_to '編集', edit_topic_comment_path(comment.topic_id, comment), class: 'btn btn-success btn-sm' if comment.user_id == current_user.id
            = link_to '削除', topic_comment_path(comment.topic_id, comment.id), method: :delete, remote: true, class: 'btn btn-danger btn-sm' if comment.user_id == current_user.id

app/views/comments/create.js.haml
$("#comments_area").html("#{escape_javascript(render partial: 'comments/index',locals: { comments: @comments })}");
$('textarea').val('')

app/views/comments/destroy.js.haml
$("#comments_area").html("#{escape_javascript(render partial: 'comments/index',locals: { comments: @comments })}");
$('textarea').val('')

app/views/comments/edit.html.haml
.container
  .wrapper.col-md-4.col-md-offset-4.col-sm-10
    %p
      %strong コメント編集
    = form_for(@comment, url: topic_comment_path(@comment.topic, @comment)) do |f|
      .row.edit-comment
        = f.text_area :content, class: "form-control", placeholder: 'コメント...'
      .row
        = f.submit '送信', class: 'btn btn-success'
        = link_to '戻る', topics_path, class: 'btn btn-default'

app/views/comments/index.js.haml
$("#comments_area").html("#{j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic })}")
$(':text').val('')