config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only:[:index, :show]
  resources :relationships, only:[:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :conversations do
    resources :messages
  end

  resources :topics do
    resources :comments

    collection do
      post :confirm
    end
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  validates :title, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only:[:edit, :update, :destroy, :show]

  def index
    @topics = Topic.all
    @topics_ids = current_user.followed_user_ids << current_user
    @topics_follow = Topic.where(user_id: @topics_ids).reverse_order
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
      @topic = Topic.new
    end
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      flash[:success] = "Topicを作成しました！"
      # NoticeMailer.sendmail_topic(@topic).deliver
      redirect_to topics_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @topic.update(topics_params)
      flash[:info] = "Topicを更新しました！"
      redirect_to topics_path
    else
      render 'edit'
    end
  end

  def destroy
    @topic.destroy
    flash[:danger] = "Topicを削除しました！"
    redirect_to topics_path
  end

  def confirm
    @topic = Topic.new(topics_params)
    render :new if @topic.invalid?
  end

  private
  def topics_params
    params.require(:topic).permit(:title, :content, :image, :image_cache)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_topics_path
    elsif action_name == 'edit'
      topic_path
    end
  end
end

app/views/topics/_form.html.haml
.container
  .wrapper.col-md-4.col-md-offset-4.col-sm-10
    .row
      = form_for(@topic) do |f|
        = f.error_messages!
        = f.label :title
        = f.text_field :title, class: 'form-control'
        %br/
        = f.label :content
        = f.text_field :content, class: 'form-control'
        %br/
        = f.label :image
        = f.file_field :image
        = f.hidden_field :image_cache
        = f.submit "投稿", class: 'btn btn-primary btn-block'

app/views/topics/confirm.html.haml
.container
  .wrapper.col-md-4.col-md-offset-4.col-sm-10
    .row
      %h3 以下の内容で投稿する。
      = form_for(@topic) do |f|
        = f.hidden_field :title
        = f.hidden_field :content
        = f.hidden_field :image
        %p
          タイトル:#{@topic.title}
        %p
          本文:#{@topic.content}
        %p
          写真:#{@topic.image}
        = f.submit "投稿する", class: 'btn btn-primary btn-block'
      = form_for(@topic, url: new_topic_path, method: 'get') do |f|
        = f.hidden_field :title
        = f.hidden_field :content
        = f.hidden_field :image
        = f.submit "戻る", name: 'back', class: 'btn btn-default btn-block'

app/views/topics/edit.html.haml
%p#notice= notice
= render 'form'
= link_to "一覧に戻る", topics_path

app/views/topics/index.html.haml
.container
  .wrapper.col-md-8.col-md-offset-2.col-sm-10
    - flash.each do |message_type, message|
      %div{:class => "alert alert-#{message_type}"}= message
    = link_to "投稿", new_topic_path, class:'btn btn-primary'
    - @topics_follow.each do |topic|
      .row.topics
        %p.user_name= topic.user.name
        %p.profile_img= profile_img(topic.user)
        = link_to topic_path(topic) do
          %p
            %strong= topic.title
        %p= topic.content
        - if topic.image?
          %p.uplaoded_image= image_tag topic.image.url
        - if current_user.id == topic.user.id
          = link_to "編集", edit_topic_path(topic.id), class: 'btn btn-default btn-success'
          = link_to "削除", topic_path(topic.id), method: :delete, data: {confirm: '本当に削除してもよろしいですか？'}, class: 'btn btn-default btn-danger'

app/views/topics/new.html.haml
%p#notice= notice
%h2 Topicを作成する
= render 'form'
= link_to "一覧に戻る", topics_path, class: 'btn btn-default'

app/views/topics/show.html.haml
%p#notice= notice
.child.row
  .wrapper.col-md-6.col-md-offset-3.col-sm-10.col-sm-offset-1
    .row
      .topic-text
        %p.profile_img= profile_img(@topic.user)
        %p.left
          %strong= @topic.user.name
        %p.left= @topic.title
        %p.left= @topic.content
        - if @topic.image?
          %p.left= image_tag @topic.image.url
        %p.right
          %strong 作成時間:
          = @topic.created_at.strftime("%y/%m/%d %p %l:%M")
      #comments_area
        = render partial: 'comments/index', locals: { comments: @comments, topic: @topic }
      = render partial: 'comments/form', locals: { comment: @comment, topic: @topic }
      .btn
        = link_to '戻る', topics_path, class: 'btn btn-default'